/*
 HTML5 Image Enhancer
 Version: 2.1.2
 (c) 2014 DMXzone.com
 @build 29-01-2014 19:06:34
*/
(function(g){function y(a,b){this.target=a;this.init(b)}function I(a){for(var b in a)return!1;return!0}function C(a){var b=document.styleSheets,c={},e;for(e in b)try{var d=b[e].rules||b[e].cssRules,f;for(f in d)a.is(d[f].selectorText)&&(c=g.extend(c,D(d[f].style),D(a.attr("style"))))}catch(h){}c.margin&&(a=c.margin.split(/\s+/),b=a.length,c["margin-top"]||(c["margin-top"]=a[0]),c["margin-right"]||(c["margin-right"]=a[1==b?0:1]),c["margin-bottom"]||(c["margin-bottom"]=a[1==b?0:2==b?1:2]),c["margin-left"]||
(c["margin-left"]=a[1==b?0:4==b?3:1]));return c}function D(a){var b={};if(!a)return b;if(a instanceof CSSStyleDeclaration)for(var c=0;c<a.length;c++){var e;e=a[c];e="margin-left-value"==e?"margin-left":"margin-right-value"==e?"margin-right":"margin-top-value"==e?"margin-top":"margin-bottom-value"==e?"margin-bottom":"padding-left-value"==e?"padding-left":"padding-right-value"==e?"padding-right":"padding-top-value"==e?"padding-top":"padding-bottom-value"==e?"padding-bottom":e;b[e]=a.getPropertyValue(e)}else if("string"==
typeof a)for(c in a=a.split("; "),a)e=a[c].split(": "),b[e[0].toLowerCase()]=e[1];return b}function q(){this.running=!1;this.actions=[]}function J(a){function b(a){e.lastIndex=0;return e.test(a)?'"'+a.replace(e,function(a){var b=d[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function c(a,e){var d,n,u,g=e[a];switch(typeof g){case "string":return b(g);case "number":return isFinite(g)?String(g):"null";case "boolean":case "null":return String(g);
case "object":if(!g)return"null";u=[];if("[object Array]"===Object.prototype.toString.apply(g)){n=g.length;for(d=0;d<n;d+=1)u[d]=c(d,g)||"null";return n=0===u.length?"[]":"["+u.join(",")+"]"}for(d in g)Object.hasOwnProperty.call(g,d)&&(n=c(d,g))&&u.push(b(d)+":"+n);return n=0===u.length?"{}":"{"+u.join(",")+"}"}return""}var e=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,d={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",
'"':'\\"',"\\":"\\\\"};return c("",{"":a})}var K={width:"auto",minWidth:0,maxWidth:"none",border:{enabled:!1,outside:!1,position:"outer",width:1,color:"#000",gradient:{enabled:!1,type:"linear",startColor:"#000",endColor:"#333",hoverStartColor:"",hoverEndColor:"",startPos:"top",endPos:"bottom"},opacity:1,hoverColor:"",hoverOpacity:1,radius:[0,0,0,0]},description:{showAlways:!1,position:"bottom",bgColor:"#fff",bgOpacity:.75,padding:5,align:"left",fontFamily:"sans-serif",fontStyle:"",fontSize:14,color:"#000",
speed:400},filters:[],hoverFilters:[],reflection:{enabled:!1,distance:0,height:.33,opacity:.33},shadow:{enabled:!1,offsetX:3,offsetY:3,blur:5,color:"#000",opacity:.25,hoverColor:"",hoverOpacity:.25},animate:!0,speed:400},E={aqua:"rgba(0,255,255,1)",black:"rgba(0,0,0,1)",blue:"rgba(0,0,255,1)",fuchsia:"rgba(255,0,255,1)",gray:"rgba(128,128,128,1)",green:"rgba(0,128,0,1)",lime:"rgba(0,255,0,1)",maroon:"rgba(128,0,0,1)",navy:"rgba(0,0,128,1)",olive:"rgba(128,128,0,1)",purple:"rgba(128,0,128,1)",red:"rgba(255,0,0,1)",
silver:"rgba(192,192,192,1)",teal:"rgba(0,128,128,1)",white:"rgba(255,255,255,1)",yellow:"rgba(255,255,0,1)",transparent:"rgba(0,0,0,0)"},F=0,k=Math.min,l=Math.max,z=Math.pow,G=Math.sqrt,x=Math.ceil,H=Math.floor,A=Math.round,B=!!document.createElement("canvas").getContext;y.filters={saturation:function(a,b){for(var c=a.data,e=-1*(parseFloat(b)||.3),d=0,f=c.length;d<f;d+=4){var h=l(c[d]+c[d+1]+c[d+2]);c[d]=k(255,l(0,c[d]+A((h-c[d])*e)));c[d+1]=k(255,l(0,c[d+1]+A((h-c[d+1])*e)));c[d+2]=k(255,l(0,c[d+
2]+A((h-c[d+2])*e)))}},brightness:function(a,b){var c=a.data;b=parseFloat(b)||.3;for(var e=H(255*b),d=0,f=c.length;d<f;d+=4)c[d]=k(255,l(0,c[d]+e)),c[d+1]=k(255,l(0,c[d+1]+e)),c[d+2]=k(255,l(0,c[d+2]+e))},contrast:function(a,b){for(var c=a.data,e=z((100*(parseFloat(b)||.1)+100)/100,2),d=0,f=c.length;d<f;d+=4){var h=c[d],m=c[d+1],n=c[d+2],h=h/255,h=h-.5,h=h*e,h=h+.5,h=255*h;c[d]=k(255,l(0,h));m/=255;m-=.5;m*=e;m+=.5;m*=255;c[d+1]=k(255,l(0,m));n/=255;n-=.5;n*=e;n+=.5;n*=255;c[d+2]=k(255,l(0,n))}},
gamma:function(a,b){for(var c=a.data,e=l(0,parseFloat(b)||2),d=0,f=c.length;d<f;d+=4)c[d]=255*z(c[d]/255,e),c[d+1]=255*z(c[d+1]/255,e),c[d+2]=255*z(c[d+2]/255,e)},grayscale:function(a,b){for(var c=a.data,e=parseFloat(b)||1,d=0,f=c.length;d<f;d+=4){var h=A(.299*c[d]+.587*c[d+1]+.114*c[d+2]);c[d]=k(255,l(0,e*h+(1-e)*c[d]));c[d+1]=k(255,l(0,e*h+(1-e)*c[d+1]));c[d+2]=k(255,l(0,e*h+(1-e)*c[d+2]))}},invert:function(a){a=a.data;for(var b=0,c=a.length;b<c;b+=4)a[b]=255-a[b],a[b+1]=255-a[b+1],a[b+2]=255-a[b+
2]},sepia:function(a,b){for(var c,e,d,f=a.data,h=parseFloat(b)||1,m=0,n=f.length;m<n;m+=4)c=f[m],e=f[m+1],d=f[m+2],f[m]=k(255,l(0,h*(.393*c+.769*e+.189*d)+(1-h)*c)),f[m+1]=k(255,l(0,h*(.349*c+.686*e+.168*d)+(1-h)*e)),f[m+2]=k(255,l(0,h*(.272*c+.534*e+.131*d)+(1-h)*d))},noise:function(a,b){for(var c=a.data,e=l(parseInt(b)||30,0),d=0,f=c.length;d<f;d+=4){var h;h=(h=e)||1;h*=Math.random();h=H(e/2-h);c[d]=k(l(c[d]+h,0),255);c[d+1]=k(l(c[d+1]+h,0),255);c[d+2]=k(l(c[d+2]+h,0),255)}},posterize:function(a,
b){for(var c=a.data,e=k(l(parseInt(b)||5,2),255),d=256/e,e=255/(e-1),f=0,h=c.length;f<h;f+=4)c[f]=parseInt(e*parseInt(c[f]/d)),c[f+1]=parseInt(e*parseInt(c[f+1]/d)),c[f+2]=parseInt(e*parseInt(c[f+2]/d))},tint:function(a,b,c){var e;/^#?[0-9A-Fa-f]{3}$|^#?[0-9A-Fa-f]{6}$/.test(b)||(b="ffffff");a=a.data;e=b.replace("#","")||"ffffff";var d=parseFloat(c)||.3;3==e.length&&(e=e.replace(/(.)/g,"$1$1"));e=parseInt(e,16);c=(e&16711680)>>16;b=(e&65280)>>8;e&=255;for(var f=0,h=a.length;f<h;f+=4)a[f]=k(255,l(0,
d*c+(1-d)*a[f])),a[f+1]=k(255,l(0,d*b+(1-d)*a[f+1])),a[f+2]=k(255,l(0,d*e+(1-d)*a[f+2]))},blur:function(a,b){try{var c=a.width,e=c<<2,d=a.height,f=a.data,h=l(parseFloat(b)||1,0),m;0>h&&(h=0);m=2.5<=h?.98711*h-.9633:.5<=h?3.97156-4.14554*G(1-.26891*h):2*h*(3.97156-4.14554*G(.865545));var h=m*m,n=h*m,g=1.57825+2.44413*m+1.4281*h+.422205*n;m=(2.44413*m+2.85619*h+1.26661*n)/g;for(var h=-(1.4281*h+1.26661*n)/g,n=.422205*n/g,g=1-(m+h+n),v=0;3>v;v++)for(var k=0;k<d;k++){for(var p=k*e+v,q=k*e+(c-1<<2)+v,
r=f[p],s=r,t=s,w=t;p<=q;p+=4)r=g*f[p]+m*s+h*t+n*w,f[p]=r,w=t,t=s,s=r;p=k*e+(c-1<<2)+v;q=k*e+v;for(w=t=s=r=f[p];p>=q;p-=4)r=g*f[p]+m*s+h*t+n*w,f[p]=r,w=t,t=s,s=r}for(v=0;3>v;v++)for(k=0;k<c;k++){p=(k<<2)+v;q=(d-1)*e+(k<<2)+v;for(w=t=s=r=f[p];p<=q;p+=e)r=g*f[p]+m*s+h*t+n*w,f[p]=r,w=t,t=s,s=r;p=(d-1)*e+(k<<2)+v;q=(k<<2)+v;for(w=t=s=r=f[p];p>=q;p-=e)r=g*f[p]+m*s+h*t+n*w,f[p]=r,w=t,t=s,s=r}}catch(x){}}};y.prototype={init:function(a){this.config=g.extend(!0,{},K,a);var b=this;a=/https?:\/\//.test(this.target.src)&&
-1==this.target.src.indexOf(window.location.host);B&&a?(a="https:"===location.protocol,a=!this.target.src.indexOf("https:")||a?"https://img-to-json.appspot":"http://img-to-json.maxnov",g.ajax({url:a+".com/?callback=?",data:{url:escape(this.target.src)},dataType:"jsonp",timeout:3E3,success:function(a,e){this.img=new Image;this.img.onload=function(){this.width=a.width;this.height=a.height;b.initCanvas(this.img)};this.img.src=a.data},error:function(a,e){this.img=new Image;this.img.onload=function(){b.initCanvas(this.img)};
this.img.onerror=function(){console&&console.error&&console.error("Error loading image: ",this)}}})):(this.img=new Image,this.img.onload=function(){B?b.initCanvas(this.img):b.initFlash()},this.img.src=this.target.src)},isLoaded:function(){return!this.target.complete||"undefined"!=typeof this.target.naturalWidth&&0===this.target.naturalWidth?!1:!0},generateId:function(){for(var a="dmxHTML5ImageEnhancer"+ ++F;0<g("#"+a).length;)a="dmxHTML5ImageEnhancer"+ ++F;return a},getSWFHTML:function(a,b){var c=
"";navigator.plugins&&navigator.mimeTypes&&navigator.mimeTypes.length?(c='<embed type="application/x-shockwave-flash" src="'+a+'dmxHTML5ImageEnhancer.swf" width="'+this.canvasWidth+'" height="'+this.canvasHeight+'"',this.target.id&&(c+=' id="'+b+'" name="'+b+'" '),c+='wmode="transparent" allowScriptAccess="always" flashvars="id='+b+"&src="+encodeURIComponent(this.target.src)+"&desc="+encodeURIComponent(this.target.alt)+"&width="+this.imageWidth+"&height="+this.imageHeight+"&config="+escape(this.getConfig())+
'"',c+="/>"):(c='<object id="'+b+'" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" width="'+this.canvasWidth+'" height="'+this.canvasHeight+'">',c=c+('<param name="movie" value="'+a+'dmxHTML5ImageEnhancer.swf" />')+'<param name="wmode" value="transparent" />',c+='<param name="allowScriptAccess" value="always" />',c+='<param name="flashvars" value="id='+b+"&src="+encodeURIComponent(this.target.src)+"&desc="+encodeURIComponent(this.target.alt)+"&width="+this.imageWidth+"&height="+this.imageHeight+
"&config="+escape(this.getConfig())+'" />',c+="</object>");return c},initFlash:function(){var a=this;if(this.isLoaded()){"auto"==this.config.width&&(this.config.width=this.target.style.width||g(this.target).attr("width")||this.target.width);this.width=this.target.width;this.height=this.target.height;var b=this.config.border.radius;this.useRadius=0<b[0]||0<b[1]||0<b[2]||0<b[3];this.config.border.outside="inner"!==this.config.border.position;this.config.border.width2=this.config.border.width<<1;this.config.border.enabled&&
this.config.border.outside&&(this.width+=this.config.border.width2,this.height+=this.config.border.width2);this.canvasWidth=this.width-0;this.canvasHeight=this.height-0;this.imageWidth=this.width-0;this.imageHeight=this.height-0;this.config.reflection.enabled&&(this.canvasHeight+=this.height*this.config.reflection.height+this.config.reflection.distance);this.offsetY=this.offsetX=0;if(this.config.shadow.enabled){var c;c=this.config.shadow.blur;this.offsetX=Math.max(0,c-this.config.shadow.offsetX);
this.offsetY=Math.max(0,c-this.config.shadow.offsetY);b=this.config.shadow.offsetX+c;c=this.config.shadow.offsetY+c;this.canvasWidth+=this.offsetX+b;this.canvasHeight+=this.offsetY+c}b=g('script[src*="dmxHTML5ImageEnhancer.js"]');0===b.length&&(b=g('script[src*="dmxHTML5ImageEnhancer_dev.js"]'));if(0<b.length&&(b=b.attr("src"),c=b.indexOf("dmxHTML5ImageEnhancer"),-1!=c)){var e=this.target.id||this.generateId();this.canvas=g(this.getSWFHTML(b.substr(0,c),e))[0];this.container=document.createElement("div");
g(this.canvas).css({position:"absolute",pointerEvents:"none"});g(this.container).css({position:"relative",width:this.config.width}).append(this.canvas);var d=C(g(this.target));g.each("display float clear vertical-align margin-top margin-right margin-bottom margin-left".split(" "),function(){var b=d[this.toString()]||g(a.target).css(this.toString());g(a.container).css(this.toString(),"inline"==b?"inline-block":b)});g(this.container).css("width",this.config.width);g(this.target).replaceWith(this.container);
window[e]=g("#"+e)[0]}g.each(["click","mousedown","mouseup","mouseover","mouseout"],function(){g("#"+e).parent()[0]["on"+this.toString()]=a.target["on"+this.toString()]});g(window).bind({resize:function(b){a.onResize.call(a,b)}});this.setCanvasSize()}else window.setTimeout(function(){a.initFlash.call(a)},100)},initCanvas:function(a){this.canvas=document.createElement("canvas");this.width=this.target.width;this.height=this.target.height;var b=this;"auto"==this.config.width&&(this.config.width=this.target.style.width||
g(this.target).attr("width")||this.target.width);a=this.config.border.radius;this.useRadius=0!==a[0]||0!==a[1]||0!==a[2]||0!==a[3];this.config.border.outside="inner"!==this.config.border.position;this.canvas.id=this.target.id||this.generateId();this.context=this.canvas.getContext("2d");this.container=document.createElement("div");g(this.canvas).css({position:"absolute",pointerEvents:"none"});g(this.container).css({position:"relative",width:this.config.width}).append(this.canvas);var c=C(g(this.target));
g.each("display float clear vertical-align margin-top margin-right margin-bottom margin-left min-width max-width".split(" "),function(){var a=c[this.toString()]||g(b.target).css(this.toString());g(b.container).css(this.toString(),"inline"==a?"inline-block":a)});g.each(["click","mousedown","mouseup","mouseover","mouseout"],function(){g(b.canvas)[0]["on"+this.toString()]=b.target["on"+this.toString()]});g(this.target).replaceWith(this.container);g(this.canvas).data("ImageEnhancer",this);this.borderColor=
this.config.border.color;this.shadowColor=this.config.shadow.color;this.drawDescription=!1;this.requireUpdate=!0;this.startTime=(new Date).getTime();this.duration=this.config.speed;this.start=this.position=0;this.txtDuration=this.config.description.speed;this.destination=this.txtStart=this.txtPosition=0;g(this.container).bind({mouseenter:function(a){b.onMouseEnter.call(b,a)},mouseleave:function(a){b.onMouseLeave.call(b,a)}});g(window).bind({resize:function(a){b.onResize.call(b,a)}});this.image=this.applyFilters(this.config.filters)||
this.target;this.setCanvasSize();a=function(){var a;this.position!=this.destination&&(a=this.destination-b.start,this.position=this.start+Math.min(Math.max((Date.now()-this.startTime)/this.duration,0),1)*a,this.requireUpdate=!0);this.txtPosition!=this.destination&&(a=this.destination-this.txtStart,this.txtPosition=this.txtStart+Math.min(Math.max((Date.now()-this.startTime)/this.txtDuration,0),1)*a,this.requireUpdate=!0);this.requireUpdate&&(this.draw.apply(b),this.requireUpdate=!1)};this.config.animate||
!this.config.description.showAlways?(q.addAction(a,this),q.start()):this.draw()},setCanvasSize:function(){var a=this.img.height/this.img.width,b=g(this.container).width(),a=x(b*a),c=0;this.width=b;this.height=a;this.config.reflection.enabled&&(c=a*this.config.reflection.height+this.config.reflection.distance);this.offsetY=this.offsetX=0;if(this.config.shadow.enabled){var e=0,d=0,f=0,h=0,d=this.config.shadow.offsetX,h=this.config.shadow.offsetY,m=this.config.shadow.blur,e=Math.max(0,m-d),d=d+m,f=Math.max(0,
m-h),h=Math.max(c,h+m);this.offsetX=e;this.offsetY=f;b+=e+d;a+=f+h}else a+=c;this.canvas.width=b;this.canvas.height=a;g(this.canvas).css({left:-this.offsetX,top:-this.offsetY});g(this.container).height(this.height)},getSize:function(a){var b={val:0,unit:"px"};"string"==typeof a&&a.indexOf("%")&&(b.unit="%");b.val=parseFloat(a)||0;return b},getConfig:function(){return J(this.config)},update:function(a){g.extend(!0,this.config,a);this.image=this.applyFilters(this.config.filters)||this.img;this.hoverImage=
this.applyFilters(this.config.hoverFilters)||this.img;this.setCanvasSize();this.draw()},onResize:function(a){this.setCanvasSize();B&&this.draw()},onMouseEnter:function(a){this.hoverImage||(this.hoverImage=this.applyFilters(this.config.hoverFilters)||this.target);this.config.animate||!this.config.description.showAlways?(this.drawDescription=!0,this.config.border.color=""!==this.config.border.hoverColor?this.config.border.hoverColor:this.config.border.color,this.config.shadow.color=""!==this.config.shadow.hoverColor?
this.config.shadow.hoverColor:this.config.shadow.color,this.requireUpdate=!0,this.startTime=(new Date).getTime(),this.start=this.position,this.destination=1,this.duration=(1-this.position)*this.config.speed,this.config.description.showAlways||(this.txtStart=this.txtPosition,this.txtDuration=(1-this.txtPosition)*this.config.description.speed)):(this.position=1,this.draw())},onMouseLeave:function(a){this.config.animate||!this.config.description.showAlways?(this.drawDescription=!1,this.config.border.color=
this.borderColor,this.config.shadow.color=this.shadowColor,this.requireUpdate=!0,this.startTime=(new Date).getTime(),this.start=this.position,this.destination=0,this.duration=this.position*this.config.speed,this.config.description.showAlways||(this.txtStart=this.txtPosition,this.txtDuration=this.txtPosition*this.config.description.speed)):(this.position=0,this.draw())},applyFilters:function(a){if(0<a.length)try{var b=document.createElement("canvas");b.width=this.img.width;b.height=this.img.height;
var c=b.getContext("2d");c.drawImage(this.img,0,0,this.img.width,this.img.height);for(var e=c.getImageData(0,0,b.width,b.height),d=0;d<a.length;d++){var f=a[d].split("|");if(y.filters[f[0]]){var h=f[0];f[0]=e;y.filters[h].apply(null,f)}}c.putImageData(e,0,0);return b}catch(m){}return null},draw:function(){var a=this.config.border.radius;this.useRadius=0!==a[0]||0!==a[1]||0!==a[2]||0!==a[3];this.context.clearRect(0,0,this.canvas.width,this.canvas.height);this.config.shadow.enabled&&this.drawShadow();
this.config.border.enabled&&this.drawBorder();this.drawImage();this.target.alt&&this.drawText(this.target.alt);this.config.reflection.enabled&&this.drawReflection()},drawBorder:function(){var a=this.context,b=this.config.border,c=this.config.border.radius;if(this.config.animate&&""!==b.hoverColor){var e=this.getRGBA(this.borderColor),d=this.getRGBA(b.hoverColor);if(0===this.position)b.color=e.toString();else if(1===this.position)b.color=d.toString();else{var f=Math.round(e.R+(d.R-e.R)*this.position),
h=Math.round(e.G+(d.G-e.G)*this.position),m=Math.round(e.B+(d.B-e.B)*this.position);b.color="rgba("+f+","+h+","+m+","+(e.A+(d.A-e.A)*this.position)+")"}}if(b.gradient.enabled){e=this.getCoord(b.gradient.startPos);f=this.getCoord(b.gradient.endPos);"radial"===b.gradient.type?(d=Math.abs(f.x-e.x),f=Math.abs(f.y-e.y),d=Math.sqrt(d*d+f*f),e=a.createRadialGradient(e.x,e.y,0,e.x,e.y,d)):e=a.createLinearGradient(e.x,e.y,f.x,f.y);if(0<this.position&&(""!==b.gradient.hoverStartColor||""!==b.gradient.hoverEndColor))if(f=
b.gradient,this.config.animate&&1>this.position){var g=this.getRGBA(f.startColor),u=this.getRGBA(""!==f.hoverStartColor?f.hoverStartColor:f.startColor),d=this.getRGBA(f.endColor),k=this.getRGBA(""!==f.hoverEndColor?f.hoverEndColor:f.endColor),f=Math.round(g.R+(u.R-g.R)*this.position),h=Math.round(g.G+(u.G-g.G)*this.position),m=Math.round(g.B+(u.B-g.B)*this.position),g=g.A+(u.A-g.A)*this.position,u=Math.round(d.R+(k.R-d.R)*this.position),l=Math.round(d.G+(k.G-d.G)*this.position),p=Math.round(d.B+(k.B-
d.B)*this.position),d=d.A+(k.A-d.A)*this.position;e.addColorStop(0,"rgba("+f+","+h+","+m+","+g+")");e.addColorStop(1,"rgba("+u+","+l+","+p+","+d+")")}else e.addColorStop(0,""!==f.hoverStartColor&&1==this.destination?f.hoverStartColor:f.startColor),e.addColorStop(1,""!==f.hoverEndColor&&1==this.destination?f.hoverEndColor:f.endColor);else e.addColorStop(0,b.gradient.startColor),e.addColorStop(1,b.gradient.endColor);b.color=e}a.save();a.fillStyle=b.color;a.globalAlpha=b.opacity;this.useRadius?this.roundedRect(this.offsetX,
this.offsetY,this.width,this.height,c[0],c[1],c[2],c[3]):(this.context.beginPath(),this.context.rect(this.offsetX,this.offsetY,this.width,this.height),this.context.closePath());a.fill();a.globalCompositeOperation="destination-out";a.fillStyle="black";a.globalAlpha=1;e=this.config.border.width<<1;this.useRadius?this.roundedRect(this.offsetX+b.width,this.offsetY+b.width,this.width-e,this.height-e,c[0],c[1],c[2],c[3],-b.width):(a.beginPath(),a.rect(this.offsetY+b.width,this.offsetY+b.width,this.width-
e,this.height-e),a.closePath());a.fill();a.restore()},drawImage:function(){var a=this.context,b=this.config.border,c=this.offsetX,e=this.offsetY,d=this.width,f=this.height;a.save();this.useRadius&&this.setClipping();b.enabled&&b.outside&&(f=this.config.border.width<<1,c+=b.width,e+=b.width,d=this.width-f,f=this.height-f);b=this.image;if(this.config.animate&&0<this.position&&1>this.position){var h=this.img.width,g=this.img.height,b=document.createElement("canvas");b.width=h;b.height=g;var n=b.getContext("2d");
n.drawImage(this.image,0,0,h,g);n.globalAlpha=this.position;n.drawImage(this.hoverImage,0,0,h,g)}else if(1===this.destination||1===this.position)b=this.hoverImage;a.globalCompositeOperation="destination-over";a.drawImage(b,c,e,d,f);a.restore()},drawReflection:function(){var a=this.context,b=this.config.reflection,c=this.canvas.width,e=this.offsetY+this.height,d=2*e,e=e+b.distance/2;a.save();a.translate(0,d+b.distance);a.scale(1,-1);a.drawImage(this.context.canvas,0,0,c,e,0,0,c,e);a.restore();a.save();
a.globalCompositeOperation="destination-out";d=a.createLinearGradient(0,e+b.distance,0,d+b.distance);d.addColorStop(0,"rgba(0, 0, 0, "+(1-b.opacity)+")");d.addColorStop(b.height,"rgba(0, 0, 0, 1)");d.addColorStop(1,"rgba(0, 0, 0, 1)");a.fillStyle=d;a.beginPath();a.rect(0,e,c,e);a.closePath();a.fill();a.restore()},drawShadow:function(){var a=this.context,b=this.config.border.radius,c=this.config.shadow,e=c.opacity;if(this.config.animate&&""!==c.hoverColor){var e=this.getRGBA(this.shadowColor),d=this.getRGBA(c.hoverColor);
if(0===this.position)c.color=e.toString(),e=c.opacity;else if(1===this.position)c.color=d.toString(),e=c.hoverOpacity;else{var f=Math.round(e.R+(d.R-e.R)*this.position),h=Math.round(e.G+(d.G-e.G)*this.position),g=Math.round(e.B+(d.B-e.B)*this.position);c.color="rgba("+f+","+h+","+g+","+(e.A+(d.A-e.A)*this.position)+")";e=c.opacity+(c.hoverOpacity-c.opacity)*this.position}}d=this.getRGBA(c.color);if(0<c.blur){d.A/=c.blur;for(f=c.blur;0<f;--f)a.save(),a.fillStyle=d.toString(),a.globalAlpha=e,this.roundedRect(this.offsetX+
c.offsetX-f,this.offsetY+c.offsetY-f,this.width+2*f,this.height+2*f,b[0],b[1],b[2],b[3],f),a.fill(),a.restore();a.save();a.globalCompositeOperation="destination-out";a.fillStyle="#000";this.useRadius?this.roundedRect(this.offsetX+c.offsetX,this.offsetY+c.offsetY,this.width,this.height,b[0],b[1],b[2],b[3]):(a.beginPath(),a.rect(this.offsetX+c.offsetX,this.offsetY+c.offsetY,this.width,this.height),a.closePath());a.fill();a.restore()}a.save();a.fillStyle=this.getRGBA(c.color).toString();a.globalAlpha=
e;this.useRadius?this.roundedRect(this.offsetX+c.offsetX,this.offsetY+c.offsetY,this.width,this.height,b[0],b[1],b[2],b[3]):(a.beginPath(),a.rect(this.offsetX+c.offsetX,this.offsetY+c.offsetY,this.width,this.height),a.closePath());a.fill();a.restore();a.save();a.globalCompositeOperation="destination-out";a.globalAlpha=1;a.fillStyle="#000";this.useRadius?this.roundedRect(this.offsetX,this.offsetY,this.width,this.height,b[0],b[1],b[2],b[3]):(a.beginPath(),a.rect(this.offsetX,this.offsetY,this.width,
this.height),a.closePath());a.fill();a.restore()},drawText:function(a){var b=this.context,c=this.config.description,e=c.padding,d=c.padding<<1,f=[],h=this.offsetX,g=this.offsetY,n=this.width,k=c.fontSize+d,l=n-d,q=this.config.border.radius[0],f=this.config.border.radius[1],k=this.config.border.radius[2],p=this.config.border.radius[3];"string"==typeof q&&0<q.indexOf("%")&&(q=x(parseInt(q,10)/100*n));"string"==typeof f&&0<f.indexOf("%")&&(f=x(parseInt(f,10)/100*n));"string"==typeof k&&0<k.indexOf("%")&&
(k=x(parseInt(k,10)/100*n));"string"==typeof p&&0<p.indexOf("%")&&(p=x(parseInt(p,10)/100*n));this.config.border.enabled&&(n-=2*this.config.border.width,l-=2*this.config.border.width);this.useRadius&&(l-="top"===c.position?q+f:p+k);b.save();this.config.border.enabled?(f=this.config.border,this.useRadius?this.roundedRect(this.offsetX+f.width,this.offsetY+f.width,this.width-2*f.width,this.height-2*f.width,this.config.border.radius[0],this.config.border.radius[1],this.config.border.radius[2],this.config.border.radius[3],
-f.width):(b.beginPath(),b.rect(this.offsetX+f.width,this.offsetY+f.width,this.width-2*f.width,this.height-2*f.width),b.closePath())):this.useRadius?this.roundedRect(this.offsetX,this.offsetY,this.width,this.height,this.config.border.radius[0],this.config.border.radius[1],this.config.border.radius[2],this.config.border.radius[3]):(b.beginPath(),b.rect(this.offsetX,this.offsetY,this.width,this.height),b.closePath());b.clip();c.fontStyle=c.fontStyle?c.fontStyle+" ":"";b.font=c.fontStyle+c.fontSize+
"px "+c.fontFamily;b.textBaseline="top";f=this.getTextLines(a,l);k=c.fontSize*f.length+d;this.config.border.enabled&&(h+=this.config.border.width,g+=this.config.border.width);this.config.description.showAlways&&(this.txtPosition=1);"bottom"===c.position?(g+=this.height-k*this.txtPosition,this.config.border.enabled&&(g-=2*this.config.border.width)):g-=k-k*this.txtPosition;b.globalAlpha=c.bgOpacity;b.fillStyle=c.bgColor;b.fillRect(h,g,n,k);b.globalAlpha=1;b.fillStyle=c.color;h+=e;g+=e;this.useRadius&&
(a="top"===c.position?q:p,this.config.border.enabled&&(a-=this.config.border.width),a>e&&(h+=a-e));b.textAlign=c.align;"right"===b.textAlign?h+=l:"center"===b.textAlign&&(h+=l/2);for(e=0;e<f.length;++e)b.fillText(f[e],h,g+e*c.fontSize);b.restore()},getTextLines:function(a,b){var c=this.context,e=[],d,f;d=c.measureText(a).width;if(d>b){for(;d>b;){for(f=d=Math.ceil(b/d*a.length);(" "!=a.charAt(--d)||c.measureText(a.substr(0,d)).width>b)&&0<d;);if(0<d)e.push(a.substr(0,d)),a=a.substr(d+1);else{for(d=
f;" "!=a.charAt(++d)&&d<a.length-1;);if(d<a.length-1)e.push(a.substr(0,d)),a=a.substr(d+1);else break}d=c.measureText(a).width}e.push(a)}else e=[a];return e},getCoord:function(a){var b={x:this.offsetX+this.width/2,y:this.offsetY+this.height/2};-1<a.indexOf("left")&&(b.x=this.offsetX);-1<a.indexOf("right")&&(b.x=this.offsetX+this.width);-1<a.indexOf("top")&&(b.y=this.offsetY);-1<a.indexOf("bottom")&&(b.y=this.offsetY+this.height);return b},getRGBA:function(a){var b={R:0,G:0,B:0,A:1,toString:function(){return"rgba("+
this.R+","+this.G+","+this.B+","+this.A+")"}};a=a.replace(/\s*/,"");if(/^rgb/.test(a)){if(a=/^rgba?\(([01]?\d\d?|2[0-4]\d|25[0-5])\,([01]?\d\d?|2[0-4]\d|25[0-5])\,([01]?\d\d?|2[0-4]\d|25[0-5])(?:\,([01](?:\.0+)?|0?\.\d*))?\)$/.exec(a))b.R=parseInt(a[1],10)||0,b.G=parseInt(a[2],10)||0,b.B=parseInt(a[3],10)||0,b.A=parseFloat(a[4])||1}else if(/^#/.test(a))a=a.substr(1),6===a.length?(b.R=parseInt(a.substr(0,2),16)||0,b.G=parseInt(a.substr(2,2),16)||0,b.B=parseInt(a.substr(4,2),16)||0):3===a.length&&(b.R=
parseInt(a.substr(0,1)+a.substr(0,1),16)||0,b.G=parseInt(a.substr(1,1)+a.substr(1,1),16)||0,b.B=parseInt(a.substr(2,1)+a.substr(2,1),16)||0);else if(E[a.toLowerCase()])return this.getRGBA(E[a.toLowerCase()]);return b},setClipping:function(){var a=this.config.border,b=a.radius,c=a.width<<1;a.outside?this.roundedRect(this.offsetX+a.width,this.offsetY+a.width,this.width-c,this.height-c,b[0],b[1],b[2],b[3],-a.width):this.roundedRect(this.offsetX,this.offsetY,this.width,this.height,b[0],b[1],b[2],b[3]);
this.context.clip()},roundedRect:function(a,b,c,e,d,f,h,g,k){var l=this.context;k=k||0;"string"==typeof d&&0<d.indexOf("%")&&(d=x(parseInt(d,10)/100*c));"string"==typeof f&&0<f.indexOf("%")&&(f=x(parseInt(f,10)/100*c));"string"==typeof h&&0<h.indexOf("%")&&(h=x(parseInt(h,10)/100*c));"string"==typeof g&&0<g.indexOf("%")&&(g=x(parseInt(g,10)/100*c));d+=k;f+=k;h+=k;g+=k;0>d&&(d=0);0>f&&(f=0);0>h&&(h=0);0>g&&(g=0);l.beginPath();l.moveTo(a,b+d);l.lineTo(a,b+e-g);l.quadraticCurveTo(a,b+e,a+g,b+e);l.lineTo(a+
c-h,b+e);l.quadraticCurveTo(a+c,b+e,a+c,b+e-h);l.lineTo(a+c,b+f);l.quadraticCurveTo(a+c,b,a+c-f,b);l.lineTo(a+d,b);l.quadraticCurveTo(a,b,a,b+d);l.closePath()}};g.fn.dmxHTML5ImageEnhancer=function(a){var b=Array.prototype.slice.call(arguments,1);if("undefined"!=typeof Spry&&Spry.Data&&Spry.Data.regionsArray){var c=this,e=function(){g(c.selector).dmxHTML5ImageEnhancer(a)};I(Spry.Data.regionsArray)&&Spry.Data.initRegions();for(var d in Spry.Data.regionsArray)"ready"!=Spry.Data.regionsArray[d].currentState&&
window.setTimeout(e,100);return this}return this.each(function(){if("img"===this.tagName.toLowerCase()){var c;c=g(this).data("ImageEnhancer")?g(this).data("ImageEnhancer"):new y(this,a);"string"===typeof a&&c[a]&&c[a].apply(c,b)}})};window.dmxHTML5ImageEnhancerEvent=function(a,b){var c,e=g("#"+a).parent()[0];if(document.createEvent)return c=document.createEvent("HTMLEvents"),c.initEvent(b,!0,!0),!e.dispatchEvent(c);if("click"==b)return e.click(),!1;c=document.createEventObject();return e.fireEvent("on"+
b,c)};window.requestAnimFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)}}();q.instance=function(){window.$animator||(window.$animator=new q);return window.$animator};q.start=function(){q.instance().start()};q.stop=function(){q.instance().stop()};q.addAction=function(a,b,c){q.instance().addAction(a,b,c)};q.prototype={start:function(){this.running||(this.running=!0,this.tick())},stop:function(){this.running=
!1},addAction:function(a,b,c){this.actions.push({method:a,scope:b||this,args:c||[]})},tick:function(){if(this.running){for(var a=0,b=this.actions.length;a<b;++a){var c=this.actions[a];c.method.call(c.scope,c.args)}var e=this;requestAnimFrame(function(){e.tick.call(e)})}}}})(jQuery);
